language: swift
os: osx
osx_image: xcode10.2
sudo: true

matrix:
  include:
  - env: TARGET=iOS DESTINATION=iphoneos

  - env: TARGET=iOS DESTINATION=iphonesimulator

  - env: TARGET=macOS

install:
  - sudo gem update --system
  - sudo gem install  -n /usr/local/bin cocoapods
  - sudo rm -rf ~/.cocoapods/
  - git clone https://git.coding.Net/CocoaPods/Specs.git ~/.cocoapods/repos/master
  - pod setup
  # - pod repo update
  - pod install --verbose --no-repo-update

script:
  - xcodebuild -showsdks
  - if [ $TARGET == "macOS" ]; then
      xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK_macOS CODE_SIGNING_REQUIRED=NO;
    else
      if [ $DESTINATION == "iphoneos" ]; then
        xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK -configuration Release build;
      else
        xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK -configuration Release -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.2' build;
      fi
    fi
  #- ./docs.sh
